"""
Report routes.
Routes: /reports  /reports/trigger-hourly
        /reports/{report_id}/download  /reports/{report_id}
"""
import logging
from datetime import datetime, timedelta
from typing import Any, Optional

from fastapi import APIRouter, Header, HTTPException
from fastapi.responses import FileResponse, JSONResponse

from api_utils import _json_safe, _synthesize_from_hourly
from batch_processor import processor
from routes_auth import _require_admin_user
from shared_state import RESULTS_DIR

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/reports", tags=["reports"])


@router.get("")
async def list_reports(
    source_type: Optional[str] = None,
    model_type: Optional[str] = None,
    limit: int = 100,
):
    """List template-based reports generated by realtime and batch pipelines.

    Falls back to synthesizing model-report-shaped documents from the
    legacy ``hourly_reports`` collection for any hours that were not
    migrated into ``model_reports`` (e.g. because the WS server crashed
    before calling ``save_model_report``).
    """
    try:
        if not processor.db or not processor.db.connected:
            raise HTTPException(status_code=503, detail="MongoDB is not connected")

        db = processor.db.db
        query: dict[str, Any] = {}
        if source_type:
            query['source.type'] = source_type
        if model_type:
            query['model.type'] = model_type

        # ── primary collection ──────────────────────────────────────────
        cursor = (
            db['model_reports']
            .find(query)
            .sort('generated_at', -1)
            .limit(max(1, min(limit, 500)))
        )
        reports: list[dict] = [_json_safe(doc) for doc in list(cursor)]
        known_ids: set[str] = {r.get('report_id', '') for r in reports}

        # ── fallback: hourly_reports not yet in model_reports ──────────
        # Only merge if caller is not filtering by model_type (those would
        # never match 'multi-model') or explicitly requests realtime.
        include_hourly = not model_type or model_type in ('multi-model', 'realtime')
        if include_hourly and not source_type or source_type in ('realtime', None):
            hourly_query: dict[str, Any] = {}
            if source_type and source_type not in ('realtime',):
                hourly_query = {'_nonexistent': True}  # exclude

            for hdoc in (
                db['hourly_reports']
                .find(hourly_query)
                .sort('generated_at', -1)
                .limit(500)
            ):
                h = _json_safe(hdoc)
                try:
                    if isinstance(hdoc.get('hour_start'), datetime):
                        rpt_id = f"rt_hourly_{hdoc['hour_start'].strftime('%Y%m%d_%H00')}"
                    else:
                        hour_start_str = h.get('hour_start') or ''
                        rpt_id = f"rt_hourly_{str(hour_start_str).replace(':', '').replace('-', '').replace('T', '_')[:13]}"
                except Exception:
                    rpt_id = f"rt_hourly_{h.get('hour_start', '')}"

                if rpt_id in known_ids:
                    continue  # already included via model_reports

                synthetic = _synthesize_from_hourly(hdoc, h)
                reports.append(synthetic)
                known_ids.add(rpt_id)

        # Re-sort after merge and apply limit
        def _sort_key(r: dict):
            v = r.get('generated_at_iso') or ''
            return v

        reports.sort(key=_sort_key, reverse=True)
        reports = reports[:max(1, min(limit, 500))]

        return JSONResponse({
            'count': len(reports),
            'filters': {
                'source_type': source_type,
                'model_type': model_type,
            },
            'reports': reports,
            'source': 'mongodb:model_reports+hourly_reports',
        })
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Reports list retrieval error: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/trigger-hourly")
async def trigger_hourly_report(
    hours_back: int = 1,
    authorization: Optional[str] = Header(default=None),
):
    """Admin endpoint: manually generate hourly summaries for the past N hours.

    Useful when the WebSocket server crashed before the hour boundary was
    processed.  Requires admin role.
    """
    _require_admin_user(authorization)

    if not processor.db or not processor.db.connected:
        raise HTTPException(status_code=503, detail="MongoDB is not connected")

    hours_back = max(1, min(hours_back, 24))
    current_hour = datetime.utcnow().replace(minute=0, second=0, microsecond=0)
    results = []

    for i in range(1, hours_back + 1):
        hour_start = current_hour - timedelta(hours=i)
        try:
            result = processor.db.summarize_and_cleanup_hour(hour_start)
            results.append(result)
        except Exception as exc:
            results.append({'processed': False, 'hour_start': hour_start.isoformat(), 'reason': str(exc)})

    return JSONResponse({'triggered': len(results), 'results': results})


@router.get("/{report_id}/download")
async def download_report_pdf(report_id: str):
    """Download the pre-generated PDF for a batch report."""
    try:
        pdf_path = RESULTS_DIR / f"{report_id}_report.pdf"
        if not pdf_path.exists():
            raise HTTPException(
                status_code=404,
                detail="PDF not available for this report. The report may be realtime-generated or the batch job did not produce a PDF.",
            )
        return FileResponse(
            path=str(pdf_path),
            media_type="application/pdf",
            filename=f"{report_id}_report.pdf",
        )
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Report PDF download error: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/{report_id}")
async def get_report(report_id: str):
    """Fetch a single report document from MongoDB by its report_id.

    Checks ``model_reports`` first; falls back to ``hourly_reports`` for
    realtime hourly reports that were written there before ``save_model_report``
    could run (e.g. when the WebSocket server crashed mid-run).
    """
    try:
        if not processor.db or not processor.db.connected:
            raise HTTPException(status_code=503, detail="MongoDB is not connected")

        db = processor.db.db

        # Primary: full model_reports document
        doc = db['model_reports'].find_one({'report_id': report_id})
        if doc:
            return JSONResponse(_json_safe(doc))

        # Fallback: hourly_reports — reconstruct a full response
        if report_id.startswith('rt_hourly_'):
            # Parse the embedded date/hour from the report_id: rt_hourly_YYYYMMDD_HH00
            try:
                parts = report_id.split('_')  # ['rt', 'hourly', 'YYYYMMDD', 'HH00']
                date_part = parts[2]          # e.g. '20260226'
                hour_part = parts[3][:2]      # e.g. '15'
                hour_start = datetime.strptime(f"{date_part}{hour_part}", '%Y%m%d%H')
                hour_end = hour_start + timedelta(hours=1)
                hdoc = db['hourly_reports'].find_one({
                    'hour_start': {'$gte': hour_start, '$lt': hour_end}
                })
            except Exception:
                hdoc = None

            if hdoc:
                synthetic = _synthesize_from_hourly(hdoc, _json_safe(hdoc))
                return JSONResponse(synthetic)

        raise HTTPException(status_code=404, detail=f"Report '{report_id}' not found")
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Report fetch error: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


